version: "3.8"
services:
    #zookeeper:
    #    image: 'bitnami/zookeeper:latest'
    #    container_name: zookeeper
    #    hostname: zookeeper
    #    ports:
    #      - "2181:2181"
    #    environment:
    #      - JVMFLAGS=-Djute.maxbuffer=2147483647
    #      - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
         image: 'bitnami/kafka:latest'
         ports:
           - '9092:9092'
         environment:
          - KAFKA_ENABLE_KRAFT=yes
          - KAFKA_CFG_PROCESS_ROLES=broker,controller
          - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
          - KAFKA_CFG_BROKER_ID=1
          - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
          - ALLOW_PLAINTEXT_LISTENER=yes
  #kafka:
  #  image: 'bitnami/kafka:latest'
  #  container_name: kafka
  #  hostname: kafka
  #  ports:
  #    - "9093:9093"
  #  environment:
  #    - ALLOW_PLAINTEXT_LISTENER=yes
  #    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #    - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9093
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
    #volumes:
      # Both .jks and .pem files are supported
      #- './Certificates/kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      #- './Certificates/kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      #- './Certificates/kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      #- './Certificates/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      #- './Certificates/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      #- './Certificates/zookeeper.keystore.jks:/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro'
      #- './Certificates/zookeeper.truststore.jks:/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro'
